### ISSUE TITLE
Monolith font missing

### ISSUE THREAD

**Issue by mulias** [cceckman/a-place-of-honor#24]
I'm on NixOS and def don't have many extra fonts installed.

- Chrome
![Screenshot_2024-06-06_17-01-19](https://github.com/cceckman/a-place-of-honor/assets/6362861/64b8ddfa-22d5-47aa-9574-393ac5c532f0)
- Firefox
![Screenshot_2024-06-06_17-00-08](https://github.com/cceckman/a-place-of-honor/assets/6362861/6217152d-4b9c-41a6-8d55-0dd3fea2e694)

**Comment by cceckman** [comment]
Thanks for the report!

The main font (Inclusive Sans) is pulled from Google Fonts; but it will then fall back to your system's default `sans-serif`.

My guess:

- Inclusive Sans doesn't have Linear-A characters. (...as one would expect.)
- Your system default `sans-serif` also doesn't have Linear-A characters, anywhere in the fallback path.
- So, tofu!

I think there's a server-side fix: if we specify a fallback font before `sans-serif` that we know to have the Linear-A character set, we'd be confident that everyone will see it (unless they have the font-server blocked).

(We could switch to serving the fonts directly -- I did that for cceckman.com and it helped performance -- but, eh, trouble to do so.)
